---
title: Rocket.Chat Documentation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: ''
  values:
    layout: default
description: Rocket.Chat user, admin, API, integration, plugin and contributing documentation.
url: https://rocket.chat/docs
version: 101
sass:
  style: compressed
  sass_dir: _sass
plugins:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
markdown: kramdown
highlighter: rouge
liquid:
  error_mode: lax
include:
- .gitbook
exclude:
- Gemfile
- Gemfile.lock
- vendor

theme: jekyll-theme-slate